/*
* generated by Xtext
*/
package at.ac.tuwien.big.me.sw11.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SOOMLDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("at/ac/tuwien/big/me/sw11/parser/antlr/internal/InternalSOOMLDsl.tokens");
	}
}
