/*
* generated by Xtext
*/
package at.ac.tuwien.big.me.sw11.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import at.ac.tuwien.big.me.sw11.services.SOOMLDslGrammarAccess;

public class SOOMLDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private SOOMLDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected at.ac.tuwien.big.me.sw11.parser.antlr.internal.InternalSOOMLDslParser createParser(XtextTokenStream stream) {
		return new at.ac.tuwien.big.me.sw11.parser.antlr.internal.InternalSOOMLDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Pkg";
	}
	
	public SOOMLDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SOOMLDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
