
package dst3.ejb.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "jobSearchService", targetNamespace = "ws.ejb.dst3", wsdlLocation = "http://localhost:8080/dst3/jobSearchService?wsdl")
public class JobSearchService
    extends Service
{

    private final static URL JOBSEARCHSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(dst3.ejb.ws.JobSearchService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = dst3.ejb.ws.JobSearchService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/dst3/jobSearchService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/dst3/jobSearchService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        JOBSEARCHSERVICE_WSDL_LOCATION = url;
    }

    public JobSearchService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JobSearchService() {
        super(JOBSEARCHSERVICE_WSDL_LOCATION, new QName("ws.ejb.dst3", "jobSearchService"));
    }

    /**
     * 
     * @return
     *     returns JobSearchPT
     */
    @WebEndpoint(name = "JobSearchPTPort")
    public JobSearchPT getJobSearchPTPort() {
        return super.getPort(new QName("ws.ejb.dst3", "JobSearchPTPort"), JobSearchPT.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns JobSearchPT
     */
    @WebEndpoint(name = "JobSearchPTPort")
    public JobSearchPT getJobSearchPTPort(WebServiceFeature... features) {
        return super.getPort(new QName("ws.ejb.dst3", "JobSearchPTPort"), JobSearchPT.class, features);
    }

}
