/*
 * generated by Xtext
 */
package at.ac.tuwien.big.me.sw11;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SOOMLDslRuntimeModule extends at.ac.tuwien.big.me.sw11.AbstractSOOMLDslRuntimeModule {

}
