package at.ac.tuwien.infosys.aic10.registration;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.3
 * Wed Oct 13 08:09:03 CEST 2010
 * Generated source version: 2.2.3
 * 
 */
 
@WebService(targetNamespace = "http://infosys.tuwien.ac.at/aic10/registration", name = "RegistrationService")
@XmlSeeAlso({ObjectFactory.class})
public interface RegistrationService {

    @WebResult(name = "success", targetNamespace = "")
    @RequestWrapper(localName = "register_student", targetNamespace = "http://infosys.tuwien.ac.at/aic10/registration", className = "at.ac.tuwien.infosys.aic10.registration.RegisterStudent")
    @ResponseWrapper(localName = "register_studentResponse", targetNamespace = "http://infosys.tuwien.ac.at/aic10/registration", className = "at.ac.tuwien.infosys.aic10.registration.RegisterStudentResponse")
    @WebMethod(operationName = "register_student")
    public at.ac.tuwien.infosys.aic10.registration.RegisterStudentResult registerStudent(
        @WebParam(name = "studentNumber", targetNamespace = "")
        java.lang.String studentNumber,
        @WebParam(name = "lastName", targetNamespace = "")
        java.lang.String lastName,
        @WebParam(name = "programNumber", targetNamespace = "")
        java.lang.String programNumber,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password
    ) throws RegistrationException;
}
