/*
 * generated by Xtext
 */
package at.ac.tuwien.big.me.sw11.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SOOMLDslUiModule extends at.ac.tuwien.big.me.sw11.ui.AbstractSOOMLDslUiModule {
	public SOOMLDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
