
package at.ac.tuwien.infosys.aic10.ass2.process;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import at.ac.tuwien.infosys.aic10.ass2.orderprocessschema.CallbackResult;
import at.ac.tuwien.infosys.aic10.ass2.orderprocessschema.ObjectFactory;
import at.ac.tuwien.infosys.aic10.ass2.orderprocessschema.Parameters;
import at.ac.tuwien.infosys.aic10.ass2.orderprocessschema.ParametersCallback;
import at.ac.tuwien.infosys.aic10.ass2.orderprocessschema.Result;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "OrderProcessPortType", targetNamespace = "http://infosys.tuwien.ac.at/aic10/ass2/process")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OrderProcessPortType {


    /**
     * 
     * @param part1
     * @return
     *     returns at.ac.tuwien.infosys.aic10.ass2.orderprocessschema.Result
     */
    @WebMethod(operationName = "start_process")
    @WebResult(name = "result", targetNamespace = "http://infosys.tuwien.ac.at/aic10/ass2/OrderProcessSchema", partName = "part1")
    public Result startProcess(
        @WebParam(name = "parameters", targetNamespace = "http://infosys.tuwien.ac.at/aic10/ass2/OrderProcessSchema", partName = "part1")
        Parameters part1);

    /**
     * 
     * @param part1
     * @return
     *     returns at.ac.tuwien.infosys.aic10.ass2.orderprocessschema.CallbackResult
     */
    @WebMethod
    @WebResult(name = "callback_result", targetNamespace = "http://infosys.tuwien.ac.at/aic10/ass2/OrderProcessSchema", partName = "part1")
    public CallbackResult callback(
        @WebParam(name = "parameters_callback", targetNamespace = "http://infosys.tuwien.ac.at/aic10/ass2/OrderProcessSchema", partName = "part1")
        ParametersCallback part1);

}
