
package at.ac.tuwien.infosys.aic10.ass2.process;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "OrderProcessService", targetNamespace = "http://infosys.tuwien.ac.at/aic10/ass2/process", wsdlLocation = "file:/C:/Dokumente%20und%20Einstellungen/Roman/Eigene%20Dateien/NetBeansProjects/Assignment2/xml/OrderProcess.wsdl")
public class OrderProcessService
    extends Service
{

    private final static URL ORDERPROCESSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(at.ac.tuwien.infosys.aic10.ass2.process.OrderProcessService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = at.ac.tuwien.infosys.aic10.ass2.process.OrderProcessService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/Dokumente%20und%20Einstellungen/Roman/Eigene%20Dateien/NetBeansProjects/Assignment2/xml/OrderProcess.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Dokumente%20und%20Einstellungen/Roman/Eigene%20Dateien/NetBeansProjects/Assignment2/xml/OrderProcess.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ORDERPROCESSSERVICE_WSDL_LOCATION = url;
    }

    public OrderProcessService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrderProcessService() {
        super(ORDERPROCESSSERVICE_WSDL_LOCATION, new QName("http://infosys.tuwien.ac.at/aic10/ass2/process", "OrderProcessService"));
    }

    /**
     * 
     * @return
     *     returns OrderProcessPortType
     */
    @WebEndpoint(name = "OrderProcessPort")
    public OrderProcessPortType getOrderProcessPort() {
        return super.getPort(new QName("http://infosys.tuwien.ac.at/aic10/ass2/process", "OrderProcessPort"), OrderProcessPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderProcessPortType
     */
    @WebEndpoint(name = "OrderProcessPort")
    public OrderProcessPortType getOrderProcessPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://infosys.tuwien.ac.at/aic10/ass2/process", "OrderProcessPort"), OrderProcessPortType.class, features);
    }

}
