/*
* generated by Xtext
*/
package at.ac.tuwien.big.me.sw11.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class SOOMLDslOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
