/*
* generated by Xtext
*/
package at.ac.tuwien.big.me.sw11.ui.contentassist;

import at.ac.tuwien.big.me.sw11.ui.contentassist.AbstractSOOMLDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class SOOMLDslProposalProvider extends AbstractSOOMLDslProposalProvider {

}
