/*
 * generated by Xtext
 */
package at.ac.tuwien.big.me.sw11.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import at.ac.tuwien.big.me.sw11.ui.internal.SOOMLDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SOOMLDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SOOMLDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SOOMLDslActivator.getInstance().getInjector(SOOMLDslActivator.AT_AC_TUWIEN_BIG_ME_SW11_SOOMLDSL);
	}
	
}
